debug: false

server:
  error:
    whitelabel:
      enabled: false
  max-http-request-header-size: 8KB
  port: ${BE_SERVER_PORT}

spring:
  cloud:
    stream:
      bindings:
        receiveMessageFromTopicTwo-in-0:
          destination: topic-two
  threads:
    virtual:
      enabled: true
